# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('GR', 'Грызун'), ('PT', 'Птица'), ('KO', 'Кошка'), ('SO', 'Собака')], max_length=2)),
            ],
        ),
    ]
