# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171114_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
