# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171121_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to='animales/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Type'),
        ),
    ]
