# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171128_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, upload_to='types/'),
        ),
    ]
