# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='animales/'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='types/'),
        ),
    ]
