# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171128_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='image',
            new_name='_image',
        ),
    ]
