# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171206_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='_image',
            new_name='image',
        ),
    ]
